spring.application.name=capstone
spring.devtools.restart.enabled=false
# 일단 이메일 세팅용 샘플로 내 이메일 넣어둠
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=yejun032569@gmail.com
spring.mail.password=(여기는 웹 메일용 계정을 만들어놨는데 거기 웹비밀번호를 사용 못하면 네이버 이메일로 바꾸려고 비워둠.)

#보안 프로퍼티 설정
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true